const chapters={1:{title:'Genesis 1',ref:'Genesis 1:1',hebrew:'בְּרֵאשִׁית',translit:'Bereshit',honey:'God spoke, and everything beautiful began.',web:[['Genesis 1:1','In the beginning, God created the heavens and the earth.'],['Genesis 1:3','God said, “Let there be light,” and there was light.'],['Genesis 1:31','God saw everything that he had made, and, behold, it was very good.']]},2:{title:'Genesis 2',ref:'Genesis 2:7',hebrew:'עֵדֶן',translit:'Eden',honey:'God creates a place of belonging.',web:[['Genesis 2:2','On the seventh day God finished his work which he had made; and he rested.'],['Genesis 2:7','Yahweh God formed man from the dust of the ground, and breathed into his nostrils the breath of life.']]}};
let current=1;const modal=document.getElementById('modal'),content=document.getElementById('content'),effects=document.getElementById('effectLayer');
function c(){return chapters[current]}
function show(h){content.innerHTML=h;modal.classList.remove('hidden');setTimeout(setupCanvas,50)}
function tapEffect(btn){btn.classList.add('tapped');setTimeout(()=>btn.classList.remove('tapped'),220);try{navigator.vibrate&&navigator.vibrate(12)}catch(e){} const r=btn.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2; const type=btn.dataset.effect; if(type==='sparkle'||type==='page'||type==='flutter'){for(let i=0;i<8;i++)burst(x+(Math.random()*40-20),y+(Math.random()*30-15),'✨','sparkle')} if(type==='petals'||type==='flutter'){for(let i=0;i<6;i++)burst(x+(Math.random()*40-20),y,'🌸','petal')} }
function burst(x,y,ch,cls){const s=document.createElement('span');s.className=cls;s.textContent=ch;s.style.left=x+'px';s.style.top=y+'px';effects.appendChild(s);setTimeout(()=>s.remove(),1300)}
function openJourney(n=1){current=n;let x=c();show(`<h1>${x.title}</h1><div class="card honeyCard"><h2>🍯 Honey Drop</h2><p>${x.honey}</p></div><div class="split"><div class="card"><h2>WEB Bible</h2>${x.web.map(v=>`<p><b>${v[0]}</b><br>${v[1]}</p>`).join('')}</div><div class="card"><h2>CJB Parallel Bible</h2><p><i>Ready for licensed CJB text.</i></p></div></div><button class="action" onclick="openComic()">Picture Comic Book</button><button class="action" onclick="openJourney(${n===1?2:1})">${n===1?'Next: Genesis 2':'Back to Genesis 1'}</button>`)}
function openParallel(){openJourney(current)}
function openComic(){show(`<h1>Genesis 1 Picture Comic Book</h1><div class="comicPages"><div class="panel"><div class="pic">🌑</div><h2>In the Beginning</h2><p>Before anything was made, God was already there.</p><div class="bubble">Rye turns the Bible page.</div></div><div class="panel"><div class="pic">☀️</div><h2>Let There Be Light</h2><p>God spoke, and light filled the darkness.</p><div class="bubble">The forest sparkles with wonder.</div></div><div class="panel"><div class="pic">🌿</div><h2>Creation Blooms</h2><p>Plants, trees, flowers, water, birds, fish, and animals fill the world.</p><div class="bubble">Everything God made was good.</div></div><div class="panel"><div class="pic">🐶📖</div><h2>Very Good</h2><p>Rye and the forest friends gather around God's Word.</p><div class="bubble">Genesis 1:31</div></div></div>`)}
function openHoney(){show(`<h1>Honey Drops</h1><div class="card honeyCard">${c().honey}</div>`)}
function openHebrew(){show(`<h1>Hebrew Garden</h1><div class="card"><p class="hebrewWord">${c().hebrew}</p><h2>${c().translit}</h2><button class="action" onclick="speak('${c().translit}')">Hear it</button></div>`)}
function openMemory(){show(`<h1>Memory Garden</h1><div class="grid"><div class="card">Memory verse: ${c().ref}</div><div class="card">Hebrew Match: ${c().hebrew} → ${c().translit}</div><div class="card">Verse Builder</div></div>`)}
function openPrayer(){show('<h1>Prayer Garden</h1><textarea placeholder="My prayers..."></textarea>')}
function openJournal(){show('<h1>Journal Corner</h1><textarea placeholder="Write here..."></textarea>')}
function openFriends(){show('<h1>Meet My Forest Friends</h1><div class="grid"><div class="card">🐶 Rye — Page Turner</div><div class="card">🦌 Tikvah — Hope</div><div class="card">🐮 Chen — Grace</div><div class="card">🦝 Mayan — Spring</div><div class="card">🦨 Perach — Blossom</div><div class="card">🪽 Ruach — Spirit/Wind</div><div class="card">🦋 Nitzan — Blossom</div><div class="card">✨ Ziv — Radiance</div></div>')}
function openArtist(){show(`<h1>Artist Studio</h1><div id="palette" class="palette"></div><p><button class="action" onclick="brush='pencil'">Pencil</button><button class="action" onclick="brush='marker'">Marker</button><button class="action" onclick="clearCanvas()">Clear</button></p><canvas id="draw" class="drawCanvas"></canvas>`)}
function simple(t){show(`<h1>${t}</h1><div class="card">This section is connected and ready to grow.</div>`)}
const actions={genesis1:()=>openJourney(1),parallel:openParallel,honey:openHoney,hebrew:openHebrew,memory:openMemory,coloring:openArtist,comic:openComic,friends:openFriends,maps:()=>simple('Bible Maps'),timeline:()=>simple('Bible Timeline'),journal:openJournal,prayer:openPrayer,artist:openArtist,search:()=>simple('Search'),favorites:()=>simple('Favorites'),groups:()=>simple('Bible Groups'),plans:()=>simple('Reading Plans')};
document.querySelectorAll('[data-panel]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();tapEffect(b);},{passive:false});b.addEventListener('click',e=>{e.preventDefault();const fn=actions[b.dataset.panel]; if(fn)fn();});});
document.getElementById('close').onclick=()=>modal.classList.add('hidden');
function speak(t){speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
let brush='pencil',color='#4f3d36';const colors=['#4f3d36','#6f7f57','#7aa6a1','#7ab6d6','#b9a7d8','#d98b91','#c56f3f','#f4c66a','#fff6c7'];
function setupCanvas(){let pal=document.getElementById('palette');if(pal&&!pal.innerHTML)pal.innerHTML=colors.map(c=>`<button class="swatch" style="background:${c}" onclick="color='${c}'"></button>`).join('');let canvas=document.getElementById('draw');if(!canvas||canvas.dataset.ready)return;canvas.dataset.ready=1;let ctx=canvas.getContext('2d');setTimeout(()=>{let r=canvas.getBoundingClientRect();canvas.width=r.width*devicePixelRatio;canvas.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.lineCap='round'},80);let down=false,last=null;function pos(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.onpointerdown=e=>{e.preventDefault();down=true;last=pos(e)};canvas.onpointermove=e=>{if(!down)return;e.preventDefault();let p=pos(e);ctx.strokeStyle=color;ctx.lineWidth=brush==='marker'?12:4;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};canvas.onpointerup=()=>down=false}
function clearCanvas(){let c=document.getElementById('draw');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height)}
